### ISSUE TITLE
TSBToolSupreme 1.3 beta - Can't apply changes to TSB3 SNES rom

### ISSUE THREAD

**Issue by Denshadego** [BAD-AL/tsbtools#1]
Using 1.3.0.0_beta, and when trying to apply changes to a TSB3 SNES rom got this:

Error! line #46:    'RE2,star LOTULELEI,Face=0x88,#96,44,44,44,56,25,50,6,56,[17,00,06]'Invalid position! RE2
   en TSBTool.StaticUtils.CheckTSB2Args(Int32 season, String team, String position)
   en TSBTool2.TSB3Tool.SetFace(Int32 season, String team, String position, Int32 face)
   en TSBTool2.InputParser.SetDefensivePlayer(String line)
   en TSBTool2.InputParser.UpdateRoster(String line)
   en TSBTool2.InputParser.ProcessLine(String line)
   en TSBTool2.InputParser.ProcessLines(String[] lines)

Operation aborted at this point. Data not applied.

**Comment by BAD-AL** [comment]
Please include a zip file with the content used so that I can reproduce the issue.

**Comment by Denshadego** [comment]
Got it!
[Tecmo Super Bowl III - Final Edition 2020 [Browns - Ravens] (Hack).zip](https://github.com/BAD-AL/tsbtools/files/5976124/Tecmo.Super.Bowl.III.-.Final.Edition.2020.Browns.-.Ravens.Hack.zip)

**Comment by BAD-AL** [comment]
I need the text you are trying to apply.

**Comment by Denshadego** [comment]
I auto updated the player sim values as a test and then tried applying them to the rom.

**Comment by BAD-AL** [comment]
Should be fixed with new release 1.3.0.1
